2024-10-30 20:28:25,310 | INFO | "test_challenge" выполнен успешно
2024-10-30 20:28:25,311 | WARNING | Неверный тип данных для объекта Runner
Имя может быть только строкой, передано int
Traceback (most recent call last):
  File "C:\Users\KOSTA\PycharmProjects\HomeWorks\tests_12_4\tests_12_4.py", line 72, in test_run
    runner = Runner(2)
             ^^^^^^^^^
  File "C:\Users\KOSTA\PycharmProjects\HomeWorks\tests_12_4\tests_12_4.py", line 10, in __init__
    raise TypeError(f'Имя может быть только строкой, передано {type(name).__name__}')
TypeError: Имя может быть только строкой, передано int
2024-10-30 20:28:25,315 | WARNING | Неверная скорость для Runner
Скорость не может быть отрицательной, сейчас -5
Traceback (most recent call last):
  File "C:\Users\KOSTA\PycharmProjects\HomeWorks\tests_12_4\tests_12_4.py", line 62, in test_walk
    runner = Runner("Вася", -5)
             ^^^^^^^^^^^^^^^^^^
  File "C:\Users\KOSTA\PycharmProjects\HomeWorks\tests_12_4\tests_12_4.py", line 15, in __init__
    raise ValueError(f'Скорость не может быть отрицательной, сейчас {speed}')
ValueError: Скорость не может быть отрицательной, сейчас -5
